# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Regexp-Common-time
version:      0.01
version_from: time.pm
installdirs:  site
requires:
    POSIX:                         0
    Regexp::Common:                2.116
    Test::Simple:                  0.40

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
